const nominations = [
    {
        id: 1,
        title: "Кринж года",
        description: "За самые неловкие моменты года",
        nominees: [
            { id: 101, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 102, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 103, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 104, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 105, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 106, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 107, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 108, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 109, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 110, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 111, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 112, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 113, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 114, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 115, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 116, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 117, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 118, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 2,
        title: "Белерик года",
        description: "За самые громкие споры и дискуссии",
        nominees: [
            { id: 201, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 202, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 203, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 204, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 205, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 206, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 207, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 208, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 209, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 210, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 211, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 212, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 213, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 214, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 215, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 216, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 217, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 218, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 3,
        title: "Манипулятор года",
        description: "За искусное влияние на других",
        nominees: [
            { id: 301, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 302, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 303, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 304, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 305, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 306, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 307, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 308, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 309, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 310, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 311, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 312, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 313, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 314, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 315, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 316, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 317, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 318, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 4,
        title: "Лох года",
        description: "За самые невезучие ситуации",
        nominees: [
            { id: 401, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 402, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 403, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 404, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 405, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 406, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 407, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 408, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 409, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 410, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 411, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 412, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 413, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 414, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 415, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 416, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 417, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 418, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 5,
        title: "Спортсмен года",
        description: "За спортивные достижения",
        nominees: [
            { id: 501, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 502, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 503, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 504, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 505, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 506, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 507, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 508, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 509, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 510, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 511, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 512, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 513, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 514, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 515, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 516, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 517, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 518, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 6,
        title: "Модник года",
        description: "За лучший стиль и внешний вид",
        nominees: [
            { id: 601, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 602, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 603, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 604, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 605, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 606, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 607, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 608, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 609, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 610, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 611, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 612, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 613, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 614, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 615, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 616, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 617, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 618, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 7,
        title: "Авантюрист года",
        description: "За самые рискованные поступки",
        nominees: [
            { id: 701, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 702, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 703, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 704, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 705, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 706, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 707, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 708, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 709, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 710, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 711, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 712, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 713, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 714, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 715, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 716, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 717, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 718, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 8,
        title: "Контентмейкер года",
        description: "За создание лучшего контента",
        nominees: [
            { id: 801, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 802, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 803, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 804, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 805, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 806, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 807, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 808, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 809, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 810, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 811, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 812, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 813, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 814, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 815, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 816, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 817, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 818, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 10,
        title: "Фейл года",
        description: "За самые эпичные провалы",
        nominees: [
            { id: 1001, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 1002, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 1003, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 1004, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 1005, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 1006, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 1007, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 1008, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 1009, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 1010, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 1011, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 1012, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 1013, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 1014, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 1015, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 1016, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 1017, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 1018, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 11,
        title: "Мем года",
        description: "За создание самого вирального мема",
        nominees: [
            { id: 1101, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 1102, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 1103, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 1104, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 1105, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 1106, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 1107, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 1108, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 1109, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 1110, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 1111, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 1112, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 1113, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 1114, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 1115, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 1116, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 1117, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 1118, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    },
    {
        id: 12,
        title: "Активист года",
        description: "За общественную активность",
        nominees: [
            { id: 1201, name: "Абаскалов Захар", image: "images/Zakhar.jpg" },
            { id: 1202, name: "Баранников Даниил", image: "images/Daniil.jpg" },
            { id: 1203, name: "Григораш Валерия", image: "images/Valeria.jpg" },
            { id: 1204, name: "Демин Артем", image: "images/Artem.jpg" },
            { id: 1205, name: "Журавских Максим", image: "images/Maksik.jpg" },
            { id: 1206, name: "Ефремова Анастасия", image: "images/NastyaEF.jpg" },
            { id: 1207, name: "Закиржанова Ульяна", image: "images/Ulya.jpg" },
            { id: 1208, name: "Захарьев Максим", image: "images/Maksim.jpg" },
            { id: 1209, name: "Комкова Вероника", image: "images/Veronika.jpg" },
            { id: 1210, name: "Комков Евгений", image: "images/Zhenya.jpg" },
            { id: 1211, name: "Кузина Алеся", image: "images/Alesya.jpg" },
            { id: 1212, name: "Лугинин Владислав", image: "images/Vlad.jpg" },
            { id: 1213, name: "Максимов Сергей", image: "images/Serega.jpg" },
            { id: 1214, name: "Молдованов Матвей", image: "images/Motya.jpg" },
            { id: 1215, name: "Пилипенко Анастасия", image: "images/NastyaPIL.jpg" },
            { id: 1216, name: "Ульченко Яна", image: "images/Yana.jpg" },
            { id: 1217, name: "Федотов Илья", image: "images/Ilya.jpg" },
            { id: 1218, name: "Шолохов Алексей", image: "images/Leha.jpg" }
        ]
    }
];

// Глобальная переменная для доступа к номинациям
window.nominations = nominations;